MERGE INTO workspace.silver.ref_text_fixes
USING (
  SELECT col1 AS field, col2 AS bad_value, col3 AS good_value
  FROM VALUES
    ('city','Berl�n','Berlín'),
    ('city','S�o Paulo','São Paulo'),
    ('city','Le�n','León'),
    ('city','Ju�rez','Juárez'),
    ('city','Bogot�','Bogotá'),
    ('city','Dubl�n','Dublín'),
    ('city','Rang�n','Rangún'),
    ('city','M�rida','Mérida'),
    ('city','Shangh�i','Shanghái'),
    ('city','Holgu�n','Holguín'),
    ('city','Se�l','Seúl'),
    ('city','Coyoac�n','Coyoacán'),
    ('city','Camag�ey','Camagüey'),
    ('city','San Pedro de Macor�s','San Pedro de Macorís'),
    ('city','Medell�n','Medellín'),
    ('city','Quer�taro','Querétaro'),
    ('city','Bras�lia','Brasília'),
    ('city','Culiac�n','Culiacán'),
    ('city','C�rdoba','Córdoba'),
    ('city','Guant�namo','Guantánamo'),
    ('city','G�mez Palacio','Gómez Palacio'),
    ('city','Pek�n','Pekín'),
    ('city','Pinar del R�o','Pinar del Río'),
    ('city','San Luis Potos�','San Luis Potosí'),
    ('city','Estel�','Estelí'),
    ('city','San Francisco de Macor�s','San Francisco de Macorís'),
    ('city','Torre�n','Torreón'),
    ('city','Tuxtla Guti�rrez','Tuxtla Gutiérrez'),
    ('city','Canc�n','Cancún'),
    ('city','Arraij�n','Arraiján'),
    ('city','Consolaci�n del Sur','Consolacion del Sur'),
    ('city','San Mart�n','San Martin'),
    ('city','Ciego de �vila','Ciego de Avila'),
    ('city','San Jos� de las Lajas','San Jose de las Lajas'),
    ('city','J�rkov','Jarkov'),
    ('city','S�o Miguel dos Campos','Sao Miguel dos Campos'),
    ('city','C�cuta','Cucuta'),
    ('city','Antiguo Cuscatl�n','Antiguo Cuscatlan'),
    ('city','Or�n','Oran'),
    ('city','Cheli�binsk','Cheliabinsk'),
    ('city','Montr�al','Montreal'),
    ('city','Amatitl�n','Amatitlan'),
    ('city','Sancti Sp�ritus','Sancti Spiritus'),
    ('city','Col�n','Colon'),
    ('city','Goi�nia','Goiania'),
    ('city','Ararangu�','Ararangua'),
    ('city','C�rdenas','Cardenas'),
    ('city','V�nnytsia','Vinnytsia'),
    ('city','A�u','Acu'),
    ('city','Jo�o Pessoa','Joao Pessoa'),
    ('city','Jerusal�n','Jerusalen'),
    ('city','Tehuac�n','Tehuacan'),
    ('city','Nicol�s Romero','Nicolas Romero'),
    ('city','Chisin�u','Chisinau'),
    ('city','Macap�','Macapa'),
    ('city','S�o Lu�s','Sao Luis'),
    ('city','Aragua�na','Araguaina'),
    ('city','Obreg�n','Obregon'),
    ('city','San Andr�s Tuxtla','San Andres Tuxtla'),
    ('city','Gona�ves','Goncalves'),
    ('city','Acu�a','Acuna'),
    ('city','Ibagu�','Ibague'),
    ('city','Ribeir�o Preto','Ribeirao Preto'),
    ('city','Zany�n','Zanyon'),
    ('city','San Crist�bal de Las Casas','San Cristobal de Las Casas'),
    ('city','Vit�ria','Vitoria'),
    ('city','Teher�n','Teheran'),
    ('city','San Francisco del Rinc�n','San Francisco del Rincon'),
    ('city','Ban�','Bani'),
    ('city','Astan�','Astana'),
    ('city','Hamad�n','Hamadan'),
    ('city','Itaja�','Itajai'),
    ('city','S�o Gon�alo','Sao Goncalo'),
    ('city','Chapec�','Chapeco'),
    ('city','Macei�','Maceio'),
    ('city','Taubat�','Taubate'),
    ('city','Heroica Zit�cuaro','Heroica Zitacuaro'),
    ('city','G�mel','Gomel'),
    ('city','Soledad D�ez Guti�rrez','Soledad Diez Gutierrez'),
    ('city','Tecom�n','Tecoman'),
    ('city','Presidencia Roque S�enz Pe�a','Presidencia Roque Saenz Pena'),
    ('city','Balne�rio Cambori�','Balneario Camboriu'),
    ('city','Oca�a','Ocana'),
    ('city','Quixad�','Quixada'),
    ('city','Jequi�','Jequie'),
    ('city','Namang�n','Namangan'),
    ('city','T�nez','Tunez'),
    ('city','Fay�n','Fayon'),
    ('city','Santo Andr�','Santo Andre'),
    ('city','S�o Bernardo do Campo','Sao Bernardo do Campo'),
    ('city','S�o Leopoldo','Sao Leopoldo'),
    ('city','Maring�','Maringa'),
    ('city','Vor�nezh','Voronezh'),
    ('city','Oriximin�','Oriximina'),
    ('city','Astrac�n','Astracan'),
    ('city','Jos� Bonif�cio','Jose Bonifacio'),
    ('city','Boa Esperan�a','Boa Esperanca'),
    ('city','Fresnillo de Gonz�lez Echeverr�a','Fresnillo de Gonzalez Echeverria'),
    ('city','Santana de Parna�ba','Santana de Parnaiba'),
    ('city','B�lgorod','Belgorod'),
    ('city','San Nicol�s de los Arroyos','San Nicolas de los Arroyos'),
    ('city','Mossor�','Mossoro'),
    ('city','Bis�u','Bissau'),
    ('city','Ita�na','Itauna'),
    ('city','San Luis R�o Colorado','San Luis Rio Colorado'),
    ('city','Cuiab�','Cuiaba'),
    ('city','Cama�ari','Camacari'),
    ('city','Ca�ador','Cacador'),
    ('city','Jiz�n','Jizan'),
    ('city','Kostan�i','Kostanai'),
    ('city','Zhyt�myr','Zhytomyr'),
    ('city','Vi�a del Mar','Vina del Mar'),
    ('city','Ibi�na','Ibiuna'),
    ('city','Tup�','Tupa'),
    ('city','San Juan del R�o','San Juan del Rio'),
    ('city','El Lim�n','El Limon'),
    ('city','Teres�polis','Teresopolis'),
    ('city','Bah�a Blanca','Bahia Blanca'),
    ('city','Tiangu�','Tiangua'),
    ('city','Petr�polis','Petropolis'),
    ('city','Valpara�so','Valparaiso'),
    ('city','Graja�','Grajau'),
    ('city','Mor�n','Moron'),
    ('city','Paranagu�','Paranagua'),
    ('city','Potos�','Potosi'),
    ('city','Guaratinguet�','Guaratingueta'),
    ('city','Matur�n','Maturin'),
    ('city','Ocotl�n','Ocotlan'),
    ('city','Lora del R�o','Lora del Rio'),
    ('city','Valpara�so de Goi�s','Valparaiso de Goias'),
    ('city','Gravata�','Gravatai'),
    ('city','Garza Garc�a','Garza Garcia'),
    ('city','Ja�','Jau'),
    ('city','Guzm�n','Guzman'),
    ('city','Tabo�o da Serra','Taboao da Serra'),
    ('city','S�o Benedito','Sao Benedito'),
    ('city','Cassil�ndia','Cassilandia'),
    ('city','Apatzing�n de la Constituci�n','Apatzingan de la Constitucion'),
    ('city','Vlad�mir','Vladimir'),
    ('city','Ara�atuba','Aracatuba'),
    ('city','S�o Pedro da Aldeia','Sao Pedro da Aldeia'),
    ('city','Chill�n','Chillon'),
    ('city','Jundia�','Jundiai'),
    ('city','Francisco Beltr�o','Francisco Beltrao'),
    ('city','Bol�var','Bolivar'),
    ('city','Jers�n','Jerson'),
    ('city','Neuqu�n','Neuquen'),
    ('city','Sahuayo de Jos� Mar�a Morelos','Sahuayo de Jose Maria Morelos'),
    ('city','Jamund�','Jamundi'),
    ('city','Karagand�','Karaganda'),
    ('city','Cuman�','Cumana'),
    ('city','Cuautitl�n','Cuautitlan'),
    ('city','Santar�m','Santarem'),
    ('city','Los �ngeles','Los Angeles'),
    ('city','Bragan�a Paulista','Braganca Paulista'),
    ('city','Paran�','Parana'),
    ('city','Jacare�','Jacarei'),
    ('city','K�tahya','Kutahya'),
    ('city','Bag�','Bage'),
    ('city','Crici�ma','Criciuma'),
    ('city','Mau�','Maua'),
    ('city','Sim�es Filho','Simoes Filho'),
    ('city','�st� nad Labem','Usti nad Labem'),
    ('city','C�a','Cua'),
    ('city','Sumar�','Sumare'),
    ('city','Asunci�n','Asuncion'),
    ('city','Ibirit�','Ibirite'),
    ('city','�guas Lindas de Goi�s','Aguas Lindas de Goias'),
    ('city','Niter�i','Niteroi'),
    ('city','Teziutl�n','Teziutlan'),
    ('city','Tern�pil','Ternopil'),
    ('city','Ac�mbaro','Acambaro'),
    ('city','Rub�','Rubi'),
    ('city','San Crist�bal','San Cristobal'),
    ('city','Bento Gon�alves','Bento Goncalves'),
    ('city','Bug�a','Buga'),
    ('city','S�o Jos� dos Campos','Sao Jose dos Campos'),
    ('city','Qazv�n','Qazvin'),
    ('city','Ji-Paran�','Ji-Parana'),
    ('city','Rol�ndia','Rolandia'),
    ('city','Po�os de Caldas','Pocos de Caldas'),
    ('city','Guaruj�','Guaruja'),
    ('city','Vit�ria da Conquista','Vitoria da Conquista'),
    ('city','Quibd�','Quibdo'),
    ('city','Copiap�','Copiapo'),
    ('city','An�polis','Anapolis'),
    ('city','Facatativ�','Facatativa'),
    ('city','Pa�o do Lumiar','Paco do Lumiar'),
    ('city','Divin�polis','Divinopolis'),
    ('city','Uberl�ndia','Uberlandia'),
    ('city','S�o Vicente','Sao Vicente'),
    ('city','Vit�ria de Santo Ant�o','Vitoria de Santo Antao'),
    ('city','Hradec Kr�lov�','Hradec Kralove'),
    ('city','Iju�','Ijui'),
    ('city','B�char','Bechar'),
    ('city','Barra do Pira�','Barra do Pirai'),
    ('city','Cox�s B?z?r','Coxs Bazar'),
    ('city','Catal�o','Catalao'),
    ('city','Le Pr�-Saint-Gervais','Le Pre-Saint-Gervais'),
    ('city','Concepci�n del Uruguay','Concepcion del Uruguay'),
    ('city','Gir�n','Giron'),
    ('city','Len��is Paulista','Lencois Paulista'),
    ('city','Tatu�','Tatui'),
    ('city','�anakkale','Canakkale'),
    ('city','C�rtama','Cartama'),
    ('city','R�o Bravo','Rio Bravo'),
    ('city','Ilh�us','Ilheus'),
    ('city','Bing�l','Bingol'),
    ('city','Camb�','Cambe'),
    ('city','Bud�nnovsk','Budonnovsk'),
    ('city','Gravat�','Gravata'),
    ('city','Serop�dica','Seropedica'),
    ('city','V�rzea Grande','Varzea Grande'),
    ('city','L�bano','Libano'),
    ('city','Paysand�','Paysandu'),
    ('city','Arauc�ria','Araucaria'),
    ('city','Lambar�','Lambare'),
    ('city','San Jos� de Guanipa','San Jose de Guanipa'),
    ('city','Guimar�es','Guimaraes'),
    ('city','Palho�a','Palhoca'),
    ('city','Apartad�','Apartado'),
    ('city','Patroc�nio','Patrocinio'),
    ('city','L�zaro C�rdenas','Lazaro Cardenas'),
    ('city','Jata�','Jatai'),
    ('city','Eun�polis','Eunapolis'),
    ('city','Cubat�o','Cubatao'),
    ('city','G�nzburg','Gunzburg'),
    ('city','Ci�naga','Cienaga'),
    ('city','El Aai�n','El Aaiun'),
    ('city','Guam�chil','Guamuchil'),
    ('city','Carapicu�ba','Carapicuiba'),
    ('city','Semn�n','Semnan'),
    ('city','Jun�n','Junin'),
    ('city','Monter�a','Monteria'),
    ('city','Rondon�polis','Rondonopolis'),
    ('city','M�con','Macon'),
    ('city','Upplands V�sby','Upplands Vasby'),
    ('city','S�te','Sete')
) s
ON workspace.silver.ref_text_fixes.field = s.field
AND workspace.silver.ref_text_fixes.bad_value = s.bad_value
WHEN MATCHED THEN UPDATE SET good_value = s.good_value
WHEN NOT MATCHED THEN INSERT (field, bad_value, good_value)
VALUES (s.field, s.bad_value, s.good_value);
