--- Fact- Sales---
SELECT
  COUNT(*) AS fact_rows,

  SUM(IFF(d.DATE_KEY IS NULL, 1, 0))        AS missing_dim_date,
  SUM(IFF(c.CUSTOMER_ID IS NULL, 1, 0))     AS missing_dim_customer,
  SUM(IFF(p.PRODUCT_CARD_ID IS NULL, 1, 0)) AS missing_dim_product,
  SUM(IFF(cat.CATEGORY_ID IS NULL, 1, 0))   AS missing_dim_category,
  SUM(IFF(dep.DEPARTMENT_ID IS NULL, 1, 0)) AS missing_dim_department,
  SUM(IFF(g.GEO_KEY IS NULL, 1, 0))         AS missing_dim_geo,
  SUM(IFF(ch.CHANNEL_KEY IS NULL, 1, 0))    AS missing_dim_channel,
  SUM(IFF(b.DISCOUNT_BAND_KEY IS NULL, 1, 0)) AS missing_dim_discount_band
FROM DATACO.GOLD.FACT_SALES f
LEFT JOIN DATACO.GOLD.DIM_DATE d
  ON f.ORDER_DATE_KEY = d.DATE_KEY
LEFT JOIN DATACO.GOLD.DIM_CUSTOMER c
  ON f.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN DATACO.GOLD.DIM_PRODUCT p
  ON f.PRODUCT_CARD_ID = p.PRODUCT_CARD_ID
LEFT JOIN DATACO.GOLD.DIM_CATEGORY cat
  ON f.CATEGORY_ID = cat.CATEGORY_ID
LEFT JOIN DATACO.GOLD.DIM_DEPARTMENT dep
  ON f.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT JOIN DATACO.GOLD.DIM_GEO g
  ON f.GEO_KEY = g.GEO_KEY
LEFT JOIN DATACO.GOLD.DIM_CHANNEL ch
  ON f.CHANNEL_KEY = ch.CHANNEL_KEY
LEFT JOIN DATACO.GOLD.DIM_DISCOUNT_BAND b
  ON f.DISCOUNT_BAND_KEY = b.DISCOUNT_BAND_KEY;



--- Fact-Fulfilment---
SELECT
  COUNT(*) AS fact_rows,

  SUM(IFF(d_order.DATE_KEY IS NULL, 1, 0))  AS missing_dim_order_date,
  SUM(IFF(d_ship.DATE_KEY IS NULL, 1, 0))   AS missing_dim_ship_date,
  SUM(IFF(c.CUSTOMER_ID IS NULL, 1, 0))     AS missing_dim_customer,
  SUM(IFF(p.PRODUCT_CARD_ID IS NULL, 1, 0)) AS missing_dim_product,
  SUM(IFF(cat.CATEGORY_ID IS NULL, 1, 0))   AS missing_dim_category,
  SUM(IFF(dep.DEPARTMENT_ID IS NULL, 1, 0)) AS missing_dim_department,
  SUM(IFF(g.GEO_KEY IS NULL, 1, 0))         AS missing_dim_geo,
  SUM(IFF(ch.CHANNEL_KEY IS NULL, 1, 0))    AS missing_dim_channel
FROM DATACO.GOLD.FACT_FULFILMENT f
LEFT JOIN DATACO.GOLD.DIM_DATE d_order
  ON f.ORDER_DATE_KEY = d_order.DATE_KEY
LEFT JOIN DATACO.GOLD.DIM_DATE d_ship
  ON f.SHIP_DATE_KEY = d_ship.DATE_KEY
LEFT JOIN DATACO.GOLD.DIM_CUSTOMER c
  ON f.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN DATACO.GOLD.DIM_PRODUCT p
  ON f.PRODUCT_CARD_ID = p.PRODUCT_CARD_ID
LEFT JOIN DATACO.GOLD.DIM_CATEGORY cat
  ON f.CATEGORY_ID = cat.CATEGORY_ID
LEFT JOIN DATACO.GOLD.DIM_DEPARTMENT dep
  ON f.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT JOIN DATACO.GOLD.DIM_GEO g
  ON f.GEO_KEY = g.GEO_KEY
LEFT JOIN DATACO.GOLD.DIM_CHANNEL ch
  ON f.CHANNEL_KEY = ch.CHANNEL_KEY;
